name: Deploy
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Версия релиза для деплоя'
        required: true
        type: string

jobs:
  verify-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY_ID }}
    steps:
      - name: Check image exists
        env:
          YC_OAUTH_TOKEN: ${{ secrets.YC_OAUTH_TOKEN }}
        run: |
          echo "$YC_OAUTH_TOKEN" | docker login \
            --username oauth \
            --password-stdin \
            cr.yandex
          
          IMAGE_TAG="${{ github.event.inputs.release_version }}_latest"
          if docker manifest inspect $REGISTRY/app:$IMAGE_TAG > /dev/null; then
            echo "Image $REGISTRY/app:$IMAGE_TAG exists"
          else
            echo "Error: Image $REGISTRY/app:$IMAGE_TAG not found!"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: verify-image
    env:
      REGISTRY: ${{ secrets.REGISTRY_ID }}
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chmod 666 /var/run/docker.sock || true
            
            echo "${{ secrets.YC_OAUTH_TOKEN }}" | docker login \
              --username oauth \
              --password-stdin \
              cr.yandex
            
            IMAGE_TAG="${{ github.event.inputs.release_version }}_latest"
            docker pull ${{ env.REGISTRY }}/app:$IMAGE_TAG
            
            docker stop app || true
            docker rm app || true
            
            docker run -d \
              --name app \
              -p 3000:3000 \
              ${{ env.REGISTRY }}/app:$IMAGE_TAG
            
            sleep 5
            docker ps --filter "name=app" --format "table {{.Names}}\t{{.Status}}"
            echo "Приложение доступно по адресу: http://$(curl -s ifconfig.me):3000/hw/store"
      - name: Add deployment comment to issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BASE_VERSION=$(echo "${{ github.event.inputs.release_version }}" | sed 's/_fix.*//')

          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=all")

          ISSUE_ID=$(echo "$RESPONSE" | jq -r --arg title "Release v$BASE_VERSION" '.[] | select(.title == $title) | .number')

          if [ -z "$ISSUE_ID" ]; then
            NEW_ISSUE_JSON='{"title":"Release v'$BASE_VERSION'", "body":"Automatic issue created for deployment tracking"}'
            NEW_ISSUE=$(curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d "$NEW_ISSUE_JSON" \
              "https://api.github.com/repos/${{ github.repository }}/issues")
            ISSUE_ID=$(echo "$NEW_ISSUE" | jq -r '.number')
            echo "Created new issue #$ISSUE_ID"
          fi

          COMMENT=$(cat <<EOF
          🚀 **Deployed to production**

          **Release version:** ${{ github.event.inputs.release_version }}
          **Docker image:** ${{ env.REGISTRY }}/app:${{ github.event.inputs.release_version }}_latest
          **Deployed at:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')
          **Deployed by:** ${{ github.actor }}
          **Access URL:** http://${{ secrets.VM_IP }}:3000/hw/store
          EOF
          )

          ESCAPED_COMMENT=$(jq -n --arg comment "$COMMENT" '$comment')

          COMMENT_JSON="{\"body\":$ESCAPED_COMMENT}"

          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$COMMENT_JSON" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_ID/comments"

          echo "Added deployment comment to issue #$ISSUE_ID"